#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
DIST_DIR=${1:-"$ROOT_DIR/dist"}
OUTPUT_SCRIPT=$DIST_DIR/orport-guard
OUTPUT_CONFIG=$DIST_DIR/orport-guard.conf.example
OUTPUT_SUMS=$DIST_DIR/SHA256SUMS
MODULES="core discovery hook runtime status cli"
TMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/orport-guard-release.XXXXXX")
HEAD_FILE=$TMP_DIR/head.sh
TAIL_FILE=$TMP_DIR/tail.sh

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT HUP INT TERM

mkdir -p "$DIST_DIR"

grep -Fqx '. "$ROOT_DIR/lib/pf.sh"' "$ROOT_DIR/bin/orport-guard" ||
  { printf 'error: bundler could not find pf loader in bin/orport-guard\n' >&2; exit 1; }
grep -Fqx '. "$ROOT_DIR/lib/cli.sh"' "$ROOT_DIR/bin/orport-guard" ||
  { printf 'error: bundler could not find cli loader in bin/orport-guard\n' >&2; exit 1; }

awk '
  /^\.[[:space:]]+"\$ROOT_DIR\/lib\/pf\.sh"$/ { split_seen = 1; next }
  /^\.[[:space:]]+"\$ROOT_DIR\/lib\/cli\.sh"$/ { split_seen = 1; next }
  {
    if (split_seen) {
      print >> tail_file
    } else {
      print >> head_file
    }
  }
' head_file="$HEAD_FILE" tail_file="$TAIL_FILE" "$ROOT_DIR/bin/orport-guard"

{
  cat "$HEAD_FILE"
  printf '\n# Bundled modules generated by scripts/build-release.sh\n'
  for module in $MODULES; do
    printf '\n# --- lib/%s.sh ---\n' "$module"
    cat "$ROOT_DIR/lib/$module.sh"
  done
  printf '\n# --- bin/orport-guard body ---\n'
  cat "$TAIL_FILE"
} >"$OUTPUT_SCRIPT"

chmod +x "$OUTPUT_SCRIPT"
cp "$ROOT_DIR/etc/orport-guard.conf" "$OUTPUT_CONFIG"

(
  cd "$DIST_DIR"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$(basename "$OUTPUT_SCRIPT")" "$(basename "$OUTPUT_CONFIG")" >"$OUTPUT_SUMS"
  else
    shasum -a 256 "$(basename "$OUTPUT_SCRIPT")" "$(basename "$OUTPUT_CONFIG")" >"$OUTPUT_SUMS"
  fi
)

sh -n "$OUTPUT_SCRIPT"

printf 'built release artifact: %s\n' "$OUTPUT_SCRIPT"
printf 'wrote sample config: %s\n' "$OUTPUT_CONFIG"
printf 'wrote checksums: %s\n' "$OUTPUT_SUMS"
